[theme]
primaryColor = "#087F8C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F6F7"
textColor = "#132D39"
font = "sans serif"

[server]
headless = true
maxUploadSize = 10

[browser]
gatherUsageStats = false
